# List of companies to initialize the crawler with
# Each company should have a name and website URL
companies:
  - name: "Igenius"
    url: "https://www.igenius.ai"
  - name: "prima"
    url: "https://www.helloprima.com"
  - name: "casavo"
    url: "https://www.casavo.com"
  - name: "xtreamers"
    url: "https://xtreamers.io"
  - name: "agilelab"
    url: "https://www.agilelab.it"
  - name: "satispay"  
    url: "https://www.satispay.com/it-it"
  - name: "weroad"
    url: "https://www.weroad.it"
  - name: "intella"
    url: "https://www.intella.tech"
  - name: "fiscozen"
    url: "https://www.fiscozen.it"
  - name: "generali"
    url: "https://www.generali.it"
  - name: "bonusx"
    url: "https://bonusx.it"
  - name: "vedrai"
    url: "https://vedrai.com"
  - name: "octopus"
    url: "https://octopusenergy.it"
  - name: "hintogroup"
    url: "https://www.hintogroup.eu"
  - name: "quantyca"
    url: "https://www.quantyca.it"
  - name: "cuebiq"
    url: "https://cuebiq.com"
  - name: "ecosmic"
    url: "https://www.ecosmic.space"
  - name: "mauden" 
    url: "https://www.mauden.com"


sources:
  - https://www.greatplacetowork.it
  - https://github.com/remoteintech/remote-jobs

